name: MiniChat
version: '${project.version}'
main: net.twlghtdrgn.minichat.MiniChat
api-version: '1.20'
website: https://github.com/TwlghtDrgn/MiniChat
authors: [TwlghtDrgn]
description: A very simple chat formatting plugin for Paper
dependencies:
    server:
        TwilightLib:
            load: BEFORE
            required: true
        PlaceholderAPI:
            load: BEFORE
            required: false
        SuperVanish:
            load: BEFORE
            required: false
        PremiumVanish:
            load: BEFORE
            required: false